const ActionTypes = {
    ISLOADER: 'ISLOADER',
    ISERROR: 'ISERROR',
    CURRENTUSER: 'CURRENTUSER',
    STATS: 'STATS',
    PROFILE: 'PROFILE',
    ABOUTUS: 'ABOUTUS', 
    TASKLIST: 'TASKLIST',
    TASKDELIVERE:"TASKDELIVERED"

}
export default ActionTypes;
